//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1.ServiceReferenceSZ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Klub", Namespace="http://schemas.datacontract.org/2004/07/AIS_N3_WCF")]
    [System.SerializableAttribute()]
    public partial class Klub : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KlubIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LetoUstanovitveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NaslovField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu[] StrelciField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KlubID {
            get {
                return this.KlubIDField;
            }
            set {
                if ((this.KlubIDField.Equals(value) != true)) {
                    this.KlubIDField = value;
                    this.RaisePropertyChanged("KlubID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LetoUstanovitve {
            get {
                return this.LetoUstanovitveField;
            }
            set {
                if ((this.LetoUstanovitveField.Equals(value) != true)) {
                    this.LetoUstanovitveField = value;
                    this.RaisePropertyChanged("LetoUstanovitve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naslov {
            get {
                return this.NaslovField;
            }
            set {
                if ((object.ReferenceEquals(this.NaslovField, value) != true)) {
                    this.NaslovField = value;
                    this.RaisePropertyChanged("Naslov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu[] Strelci {
            get {
                return this.StrelciField;
            }
            set {
                if ((object.ReferenceEquals(this.StrelciField, value) != true)) {
                    this.StrelciField = value;
                    this.RaisePropertyChanged("Strelci");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StrelecVKlubu", Namespace="http://schemas.datacontract.org/2004/07/AIS_N3_WCF")]
    [System.SerializableAttribute()]
    public partial class StrelecVKlubu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ServiceReferenceSZ.Klub KlubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KlubIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ServiceReferenceSZ.Strelec StrelecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StrelecKlubIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Do {
            get {
                return this.DoField;
            }
            set {
                if ((this.DoField.Equals(value) != true)) {
                    this.DoField = value;
                    this.RaisePropertyChanged("Do");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ServiceReferenceSZ.Klub Klub {
            get {
                return this.KlubField;
            }
            set {
                if ((object.ReferenceEquals(this.KlubField, value) != true)) {
                    this.KlubField = value;
                    this.RaisePropertyChanged("Klub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KlubId {
            get {
                return this.KlubIdField;
            }
            set {
                if ((this.KlubIdField.Equals(value) != true)) {
                    this.KlubIdField = value;
                    this.RaisePropertyChanged("KlubId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Od {
            get {
                return this.OdField;
            }
            set {
                if ((this.OdField.Equals(value) != true)) {
                    this.OdField = value;
                    this.RaisePropertyChanged("Od");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ServiceReferenceSZ.Strelec Strelec {
            get {
                return this.StrelecField;
            }
            set {
                if ((object.ReferenceEquals(this.StrelecField, value) != true)) {
                    this.StrelecField = value;
                    this.RaisePropertyChanged("Strelec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StrelecKlubID {
            get {
                return this.StrelecKlubIDField;
            }
            set {
                if ((this.StrelecKlubIDField.Equals(value) != true)) {
                    this.StrelecKlubIDField = value;
                    this.RaisePropertyChanged("StrelecKlubID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Strelec", Namespace="http://schemas.datacontract.org/2004/07/AIS_N3_WCF")]
    [System.SerializableAttribute()]
    public partial class Strelec : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu[] KlubiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LetoRojstvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriimekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StrelecIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu[] Klubi {
            get {
                return this.KlubiField;
            }
            set {
                if ((object.ReferenceEquals(this.KlubiField, value) != true)) {
                    this.KlubiField = value;
                    this.RaisePropertyChanged("Klubi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LetoRojstva {
            get {
                return this.LetoRojstvaField;
            }
            set {
                if ((this.LetoRojstvaField.Equals(value) != true)) {
                    this.LetoRojstvaField = value;
                    this.RaisePropertyChanged("LetoRojstva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priimek {
            get {
                return this.PriimekField;
            }
            set {
                if ((object.ReferenceEquals(this.PriimekField, value) != true)) {
                    this.PriimekField = value;
                    this.RaisePropertyChanged("Priimek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StrelecID {
            get {
                return this.StrelecIDField;
            }
            set {
                if ((this.StrelecIDField.Equals(value) != true)) {
                    this.StrelecIDField = value;
                    this.RaisePropertyChanged("StrelecID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/AIS_N3_WCF")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GesloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((this.AdminField.Equals(value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Geslo {
            get {
                return this.GesloField;
            }
            set {
                if ((object.ReferenceEquals(this.GesloField, value) != true)) {
                    this.GesloField = value;
                    this.RaisePropertyChanged("Geslo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSZ.IStrelskaZveza")]
    public interface IStrelskaZveza {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/AddKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/AddKlubResponse")]
        UnitTestProject1.ServiceReferenceSZ.AddKlubResponse AddKlub(UnitTestProject1.ServiceReferenceSZ.AddKlubRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/AddKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/AddKlubResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.AddKlubResponse> AddKlubAsync(UnitTestProject1.ServiceReferenceSZ.AddKlubRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/AddStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/AddStrelecResponse")]
        UnitTestProject1.ServiceReferenceSZ.AddStrelecResponse AddStrelec(UnitTestProject1.ServiceReferenceSZ.AddStrelecRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/AddStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/AddStrelecResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.AddStrelecResponse> AddStrelecAsync(UnitTestProject1.ServiceReferenceSZ.AddStrelecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/UpdateKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/UpdateKlubResponse")]
        bool UpdateKlub(UnitTestProject1.ServiceReferenceSZ.Klub k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/UpdateKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/UpdateKlubResponse")]
        System.Threading.Tasks.Task<bool> UpdateKlubAsync(UnitTestProject1.ServiceReferenceSZ.Klub k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/UpdateStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/UpdateStrelecResponse")]
        bool UpdateStrelec(UnitTestProject1.ServiceReferenceSZ.Strelec k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/UpdateStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/UpdateStrelecResponse")]
        System.Threading.Tasks.Task<bool> UpdateStrelecAsync(UnitTestProject1.ServiceReferenceSZ.Strelec k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/UpdateSVK", ReplyAction="http://tempuri.org/IStrelskaZveza/UpdateSVKResponse")]
        bool UpdateSVK(UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu svk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/UpdateSVK", ReplyAction="http://tempuri.org/IStrelskaZveza/UpdateSVKResponse")]
        System.Threading.Tasks.Task<bool> UpdateSVKAsync(UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu svk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DodajStrelcaVklub", ReplyAction="http://tempuri.org/IStrelskaZveza/DodajStrelcaVklubResponse")]
        UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubResponse DodajStrelcaVklub(UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DodajStrelcaVklub", ReplyAction="http://tempuri.org/IStrelskaZveza/DodajStrelcaVklubResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubResponse> DodajStrelcaVklubAsync(UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DeleteKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/DeleteKlubResponse")]
        bool DeleteKlub(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DeleteKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/DeleteKlubResponse")]
        System.Threading.Tasks.Task<bool> DeleteKlubAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DeleteStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/DeleteStrelecResponse")]
        bool DeleteStrelec(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DeleteStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/DeleteStrelecResponse")]
        System.Threading.Tasks.Task<bool> DeleteStrelecAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DeleteSVK", ReplyAction="http://tempuri.org/IStrelskaZveza/DeleteSVKResponse")]
        bool DeleteSVK(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DeleteSVK", ReplyAction="http://tempuri.org/IStrelskaZveza/DeleteSVKResponse")]
        System.Threading.Tasks.Task<bool> DeleteSVKAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnKlubi", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnKlubiResponse")]
        UnitTestProject1.ServiceReferenceSZ.Klub[] ReturnKlubi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnKlubi", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnKlubiResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.Klub[]> ReturnKlubiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnStrelci", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnStrelciResponse")]
        UnitTestProject1.ServiceReferenceSZ.Strelec[] ReturnStrelci();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnStrelci", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnStrelciResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.Strelec[]> ReturnStrelciAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnStrelecVKlubus", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnStrelecVKlubusResponse")]
        UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu[] ReturnStrelecVKlubus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnStrelecVKlubus", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnStrelecVKlubusResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu[]> ReturnStrelecVKlubusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnUseri", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnUseriResponse")]
        UnitTestProject1.ServiceReferenceSZ.User[] ReturnUseri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnUseri", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnUseriResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.User[]> ReturnUseriAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/GetKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/GetKlubResponse")]
        UnitTestProject1.ServiceReferenceSZ.Klub GetKlub(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/GetKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/GetKlubResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.Klub> GetKlubAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/GetStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/GetStrelecResponse")]
        UnitTestProject1.ServiceReferenceSZ.Strelec GetStrelec(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/GetStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/GetStrelecResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.Strelec> GetStrelecAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/StrelciInKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/StrelciInKlubResponse")]
        UnitTestProject1.ServiceReferenceSZ.Strelec[] StrelciInKlub(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/StrelciInKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/StrelciInKlubResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.Strelec[]> StrelciInKlubAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/KlubiOdStrelca", ReplyAction="http://tempuri.org/IStrelskaZveza/KlubiOdStrelcaResponse")]
        UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaResponse KlubiOdStrelca(UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/KlubiOdStrelca", ReplyAction="http://tempuri.org/IStrelskaZveza/KlubiOdStrelcaResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaResponse> KlubiOdStrelcaAsync(UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/CheckUser", ReplyAction="http://tempuri.org/IStrelskaZveza/CheckUserResponse")]
        UnitTestProject1.ServiceReferenceSZ.CheckUserResponse CheckUser(UnitTestProject1.ServiceReferenceSZ.CheckUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/CheckUser", ReplyAction="http://tempuri.org/IStrelskaZveza/CheckUserResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.CheckUserResponse> CheckUserAsync(UnitTestProject1.ServiceReferenceSZ.CheckUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddKlub", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddKlubRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceSZ.Klub k;
        
        public AddKlubRequest() {
        }
        
        public AddKlubRequest(UnitTestProject1.ServiceReferenceSZ.Klub k) {
            this.k = k;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddKlubResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddKlubResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddKlubResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public AddKlubResponse() {
        }
        
        public AddKlubResponse(bool AddKlubResult, int id) {
            this.AddKlubResult = AddKlubResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddStrelec", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddStrelecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceSZ.Strelec s;
        
        public AddStrelecRequest() {
        }
        
        public AddStrelecRequest(UnitTestProject1.ServiceReferenceSZ.Strelec s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddStrelecResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddStrelecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddStrelecResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public AddStrelecResponse() {
        }
        
        public AddStrelecResponse(bool AddStrelecResult, int id) {
            this.AddStrelecResult = AddStrelecResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DodajStrelcaVklub", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DodajStrelcaVklubRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceSZ.Strelec s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string kid;
        
        public DodajStrelcaVklubRequest() {
        }
        
        public DodajStrelcaVklubRequest(UnitTestProject1.ServiceReferenceSZ.Strelec s, string kid) {
            this.s = s;
            this.kid = kid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DodajStrelcaVklubResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DodajStrelcaVklubResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DodajStrelcaVklubResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public DodajStrelcaVklubResponse() {
        }
        
        public DodajStrelcaVklubResponse(bool DodajStrelcaVklubResult, int id) {
            this.DodajStrelcaVklubResult = DodajStrelcaVklubResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KlubiOdStrelca", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KlubiOdStrelcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string id;
        
        public KlubiOdStrelcaRequest() {
        }
        
        public KlubiOdStrelcaRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KlubiOdStrelcaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KlubiOdStrelcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceSZ.Klub[] KlubiOdStrelcaResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int[] trenutnoAktivni;
        
        public KlubiOdStrelcaResponse() {
        }
        
        public KlubiOdStrelcaResponse(UnitTestProject1.ServiceReferenceSZ.Klub[] KlubiOdStrelcaResult, int[] trenutnoAktivni) {
            this.KlubiOdStrelcaResult = KlubiOdStrelcaResult;
            this.trenutnoAktivni = trenutnoAktivni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UnitTestProject1.ServiceReferenceSZ.User u;
        
        public CheckUserRequest() {
        }
        
        public CheckUserRequest(UnitTestProject1.ServiceReferenceSZ.User u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CheckUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool admin;
        
        public CheckUserResponse() {
        }
        
        public CheckUserResponse(bool CheckUserResult, bool admin) {
            this.CheckUserResult = CheckUserResult;
            this.admin = admin;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStrelskaZvezaChannel : UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StrelskaZvezaClient : System.ServiceModel.ClientBase<UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza>, UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza {
        
        public StrelskaZvezaClient() {
        }
        
        public StrelskaZvezaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StrelskaZvezaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrelskaZvezaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrelskaZvezaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReferenceSZ.AddKlubResponse UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza.AddKlub(UnitTestProject1.ServiceReferenceSZ.AddKlubRequest request) {
            return base.Channel.AddKlub(request);
        }
        
        public bool AddKlub(UnitTestProject1.ServiceReferenceSZ.Klub k, out int id) {
            UnitTestProject1.ServiceReferenceSZ.AddKlubRequest inValue = new UnitTestProject1.ServiceReferenceSZ.AddKlubRequest();
            inValue.k = k;
            UnitTestProject1.ServiceReferenceSZ.AddKlubResponse retVal = ((UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza)(this)).AddKlub(inValue);
            id = retVal.id;
            return retVal.AddKlubResult;
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.AddKlubResponse> AddKlubAsync(UnitTestProject1.ServiceReferenceSZ.AddKlubRequest request) {
            return base.Channel.AddKlubAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReferenceSZ.AddStrelecResponse UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza.AddStrelec(UnitTestProject1.ServiceReferenceSZ.AddStrelecRequest request) {
            return base.Channel.AddStrelec(request);
        }
        
        public bool AddStrelec(UnitTestProject1.ServiceReferenceSZ.Strelec s, out int id) {
            UnitTestProject1.ServiceReferenceSZ.AddStrelecRequest inValue = new UnitTestProject1.ServiceReferenceSZ.AddStrelecRequest();
            inValue.s = s;
            UnitTestProject1.ServiceReferenceSZ.AddStrelecResponse retVal = ((UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza)(this)).AddStrelec(inValue);
            id = retVal.id;
            return retVal.AddStrelecResult;
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.AddStrelecResponse> AddStrelecAsync(UnitTestProject1.ServiceReferenceSZ.AddStrelecRequest request) {
            return base.Channel.AddStrelecAsync(request);
        }
        
        public bool UpdateKlub(UnitTestProject1.ServiceReferenceSZ.Klub k) {
            return base.Channel.UpdateKlub(k);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateKlubAsync(UnitTestProject1.ServiceReferenceSZ.Klub k) {
            return base.Channel.UpdateKlubAsync(k);
        }
        
        public bool UpdateStrelec(UnitTestProject1.ServiceReferenceSZ.Strelec k) {
            return base.Channel.UpdateStrelec(k);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStrelecAsync(UnitTestProject1.ServiceReferenceSZ.Strelec k) {
            return base.Channel.UpdateStrelecAsync(k);
        }
        
        public bool UpdateSVK(UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu svk) {
            return base.Channel.UpdateSVK(svk);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSVKAsync(UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu svk) {
            return base.Channel.UpdateSVKAsync(svk);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubResponse UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza.DodajStrelcaVklub(UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubRequest request) {
            return base.Channel.DodajStrelcaVklub(request);
        }
        
        public bool DodajStrelcaVklub(UnitTestProject1.ServiceReferenceSZ.Strelec s, string kid, out int id) {
            UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubRequest inValue = new UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubRequest();
            inValue.s = s;
            inValue.kid = kid;
            UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubResponse retVal = ((UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza)(this)).DodajStrelcaVklub(inValue);
            id = retVal.id;
            return retVal.DodajStrelcaVklubResult;
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubResponse> DodajStrelcaVklubAsync(UnitTestProject1.ServiceReferenceSZ.DodajStrelcaVklubRequest request) {
            return base.Channel.DodajStrelcaVklubAsync(request);
        }
        
        public bool DeleteKlub(string id) {
            return base.Channel.DeleteKlub(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteKlubAsync(string id) {
            return base.Channel.DeleteKlubAsync(id);
        }
        
        public bool DeleteStrelec(string id) {
            return base.Channel.DeleteStrelec(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStrelecAsync(string id) {
            return base.Channel.DeleteStrelecAsync(id);
        }
        
        public bool DeleteSVK(string id) {
            return base.Channel.DeleteSVK(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSVKAsync(string id) {
            return base.Channel.DeleteSVKAsync(id);
        }
        
        public UnitTestProject1.ServiceReferenceSZ.Klub[] ReturnKlubi() {
            return base.Channel.ReturnKlubi();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.Klub[]> ReturnKlubiAsync() {
            return base.Channel.ReturnKlubiAsync();
        }
        
        public UnitTestProject1.ServiceReferenceSZ.Strelec[] ReturnStrelci() {
            return base.Channel.ReturnStrelci();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.Strelec[]> ReturnStrelciAsync() {
            return base.Channel.ReturnStrelciAsync();
        }
        
        public UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu[] ReturnStrelecVKlubus() {
            return base.Channel.ReturnStrelecVKlubus();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.StrelecVKlubu[]> ReturnStrelecVKlubusAsync() {
            return base.Channel.ReturnStrelecVKlubusAsync();
        }
        
        public UnitTestProject1.ServiceReferenceSZ.User[] ReturnUseri() {
            return base.Channel.ReturnUseri();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.User[]> ReturnUseriAsync() {
            return base.Channel.ReturnUseriAsync();
        }
        
        public UnitTestProject1.ServiceReferenceSZ.Klub GetKlub(string id) {
            return base.Channel.GetKlub(id);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.Klub> GetKlubAsync(string id) {
            return base.Channel.GetKlubAsync(id);
        }
        
        public UnitTestProject1.ServiceReferenceSZ.Strelec GetStrelec(string id) {
            return base.Channel.GetStrelec(id);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.Strelec> GetStrelecAsync(string id) {
            return base.Channel.GetStrelecAsync(id);
        }
        
        public UnitTestProject1.ServiceReferenceSZ.Strelec[] StrelciInKlub(string id) {
            return base.Channel.StrelciInKlub(id);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.Strelec[]> StrelciInKlubAsync(string id) {
            return base.Channel.StrelciInKlubAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaResponse UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza.KlubiOdStrelca(UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaRequest request) {
            return base.Channel.KlubiOdStrelca(request);
        }
        
        public UnitTestProject1.ServiceReferenceSZ.Klub[] KlubiOdStrelca(string id, out int[] trenutnoAktivni) {
            UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaRequest inValue = new UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaRequest();
            inValue.id = id;
            UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaResponse retVal = ((UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza)(this)).KlubiOdStrelca(inValue);
            trenutnoAktivni = retVal.trenutnoAktivni;
            return retVal.KlubiOdStrelcaResult;
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaResponse> KlubiOdStrelcaAsync(UnitTestProject1.ServiceReferenceSZ.KlubiOdStrelcaRequest request) {
            return base.Channel.KlubiOdStrelcaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestProject1.ServiceReferenceSZ.CheckUserResponse UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza.CheckUser(UnitTestProject1.ServiceReferenceSZ.CheckUserRequest request) {
            return base.Channel.CheckUser(request);
        }
        
        public bool CheckUser(UnitTestProject1.ServiceReferenceSZ.User u, out bool admin) {
            UnitTestProject1.ServiceReferenceSZ.CheckUserRequest inValue = new UnitTestProject1.ServiceReferenceSZ.CheckUserRequest();
            inValue.u = u;
            UnitTestProject1.ServiceReferenceSZ.CheckUserResponse retVal = ((UnitTestProject1.ServiceReferenceSZ.IStrelskaZveza)(this)).CheckUser(inValue);
            admin = retVal.admin;
            return retVal.CheckUserResult;
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReferenceSZ.CheckUserResponse> CheckUserAsync(UnitTestProject1.ServiceReferenceSZ.CheckUserRequest request) {
            return base.Channel.CheckUserAsync(request);
        }
    }
}
