//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.StrelskaZveza {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StrelskaZveza.IStrelskaZveza")]
    public interface IStrelskaZveza {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/AddKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/AddKlubResponse")]
        bool AddKlub(AIS_N3_WCF.Klub k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/AddKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/AddKlubResponse")]
        System.Threading.Tasks.Task<bool> AddKlubAsync(AIS_N3_WCF.Klub k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/AddStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/AddStrelecResponse")]
        ConsoleApp1.StrelskaZveza.AddStrelecResponse AddStrelec(ConsoleApp1.StrelskaZveza.AddStrelecRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/AddStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/AddStrelecResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.StrelskaZveza.AddStrelecResponse> AddStrelecAsync(ConsoleApp1.StrelskaZveza.AddStrelecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/UpdateKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/UpdateKlubResponse")]
        bool UpdateKlub(AIS_N3_WCF.Klub k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/UpdateKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/UpdateKlubResponse")]
        System.Threading.Tasks.Task<bool> UpdateKlubAsync(AIS_N3_WCF.Klub k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/UpdateStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/UpdateStrelecResponse")]
        bool UpdateStrelec(AIS_N3_WCF.Strelec k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/UpdateStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/UpdateStrelecResponse")]
        System.Threading.Tasks.Task<bool> UpdateStrelecAsync(AIS_N3_WCF.Strelec k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DodajStrelcaVklub", ReplyAction="http://tempuri.org/IStrelskaZveza/DodajStrelcaVklubResponse")]
        bool DodajStrelcaVklub(AIS_N3_WCF.Strelec s, string kid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DodajStrelcaVklub", ReplyAction="http://tempuri.org/IStrelskaZveza/DodajStrelcaVklubResponse")]
        System.Threading.Tasks.Task<bool> DodajStrelcaVklubAsync(AIS_N3_WCF.Strelec s, string kid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DeleteKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/DeleteKlubResponse")]
        bool DeleteKlub(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DeleteKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/DeleteKlubResponse")]
        System.Threading.Tasks.Task<bool> DeleteKlubAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DeleteStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/DeleteStrelecResponse")]
        bool DeleteStrelec(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/DeleteStrelec", ReplyAction="http://tempuri.org/IStrelskaZveza/DeleteStrelecResponse")]
        System.Threading.Tasks.Task<bool> DeleteStrelecAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnKlubi", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnKlubiResponse")]
        AIS_N3_WCF.Klub[] ReturnKlubi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnKlubi", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnKlubiResponse")]
        System.Threading.Tasks.Task<AIS_N3_WCF.Klub[]> ReturnKlubiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnStrelci", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnStrelciResponse")]
        AIS_N3_WCF.Strelec[] ReturnStrelci();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnStrelci", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnStrelciResponse")]
        System.Threading.Tasks.Task<AIS_N3_WCF.Strelec[]> ReturnStrelciAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnUseri", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnUseriResponse")]
        AIS_N3_WCF.User[] ReturnUseri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/ReturnUseri", ReplyAction="http://tempuri.org/IStrelskaZveza/ReturnUseriResponse")]
        System.Threading.Tasks.Task<AIS_N3_WCF.User[]> ReturnUseriAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/StrelciInKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/StrelciInKlubResponse")]
        AIS_N3_WCF.Strelec[] StrelciInKlub(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/StrelciInKlub", ReplyAction="http://tempuri.org/IStrelskaZveza/StrelciInKlubResponse")]
        System.Threading.Tasks.Task<AIS_N3_WCF.Strelec[]> StrelciInKlubAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/CheckUser", ReplyAction="http://tempuri.org/IStrelskaZveza/CheckUserResponse")]
        ConsoleApp1.StrelskaZveza.CheckUserResponse CheckUser(ConsoleApp1.StrelskaZveza.CheckUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrelskaZveza/CheckUser", ReplyAction="http://tempuri.org/IStrelskaZveza/CheckUserResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.StrelskaZveza.CheckUserResponse> CheckUserAsync(ConsoleApp1.StrelskaZveza.CheckUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddStrelec", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddStrelecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AIS_N3_WCF.Strelec s;
        
        public AddStrelecRequest() {
        }
        
        public AddStrelecRequest(AIS_N3_WCF.Strelec s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddStrelecResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddStrelecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddStrelecResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        public AddStrelecResponse() {
        }
        
        public AddStrelecResponse(bool AddStrelecResult, int id) {
            this.AddStrelecResult = AddStrelecResult;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AIS_N3_WCF.User u;
        
        public CheckUserRequest() {
        }
        
        public CheckUserRequest(AIS_N3_WCF.User u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CheckUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CheckUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool admin;
        
        public CheckUserResponse() {
        }
        
        public CheckUserResponse(bool CheckUserResult, bool admin) {
            this.CheckUserResult = CheckUserResult;
            this.admin = admin;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStrelskaZvezaChannel : ConsoleApp1.StrelskaZveza.IStrelskaZveza, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StrelskaZvezaClient : System.ServiceModel.ClientBase<ConsoleApp1.StrelskaZveza.IStrelskaZveza>, ConsoleApp1.StrelskaZveza.IStrelskaZveza {
        
        public StrelskaZvezaClient() {
        }
        
        public StrelskaZvezaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StrelskaZvezaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrelskaZvezaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrelskaZvezaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddKlub(AIS_N3_WCF.Klub k) {
            return base.Channel.AddKlub(k);
        }
        
        public System.Threading.Tasks.Task<bool> AddKlubAsync(AIS_N3_WCF.Klub k) {
            return base.Channel.AddKlubAsync(k);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.StrelskaZveza.AddStrelecResponse ConsoleApp1.StrelskaZveza.IStrelskaZveza.AddStrelec(ConsoleApp1.StrelskaZveza.AddStrelecRequest request) {
            return base.Channel.AddStrelec(request);
        }
        
        public bool AddStrelec(AIS_N3_WCF.Strelec s, out int id) {
            ConsoleApp1.StrelskaZveza.AddStrelecRequest inValue = new ConsoleApp1.StrelskaZveza.AddStrelecRequest();
            inValue.s = s;
            ConsoleApp1.StrelskaZveza.AddStrelecResponse retVal = ((ConsoleApp1.StrelskaZveza.IStrelskaZveza)(this)).AddStrelec(inValue);
            id = retVal.id;
            return retVal.AddStrelecResult;
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.StrelskaZveza.AddStrelecResponse> AddStrelecAsync(ConsoleApp1.StrelskaZveza.AddStrelecRequest request) {
            return base.Channel.AddStrelecAsync(request);
        }
        
        public bool UpdateKlub(AIS_N3_WCF.Klub k) {
            return base.Channel.UpdateKlub(k);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateKlubAsync(AIS_N3_WCF.Klub k) {
            return base.Channel.UpdateKlubAsync(k);
        }
        
        public bool UpdateStrelec(AIS_N3_WCF.Strelec k) {
            return base.Channel.UpdateStrelec(k);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateStrelecAsync(AIS_N3_WCF.Strelec k) {
            return base.Channel.UpdateStrelecAsync(k);
        }
        
        public bool DodajStrelcaVklub(AIS_N3_WCF.Strelec s, string kid) {
            return base.Channel.DodajStrelcaVklub(s, kid);
        }
        
        public System.Threading.Tasks.Task<bool> DodajStrelcaVklubAsync(AIS_N3_WCF.Strelec s, string kid) {
            return base.Channel.DodajStrelcaVklubAsync(s, kid);
        }
        
        public bool DeleteKlub(string id) {
            return base.Channel.DeleteKlub(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteKlubAsync(string id) {
            return base.Channel.DeleteKlubAsync(id);
        }
        
        public bool DeleteStrelec(string id) {
            return base.Channel.DeleteStrelec(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStrelecAsync(string id) {
            return base.Channel.DeleteStrelecAsync(id);
        }
        
        public AIS_N3_WCF.Klub[] ReturnKlubi() {
            return base.Channel.ReturnKlubi();
        }
        
        public System.Threading.Tasks.Task<AIS_N3_WCF.Klub[]> ReturnKlubiAsync() {
            return base.Channel.ReturnKlubiAsync();
        }
        
        public AIS_N3_WCF.Strelec[] ReturnStrelci() {
            return base.Channel.ReturnStrelci();
        }
        
        public System.Threading.Tasks.Task<AIS_N3_WCF.Strelec[]> ReturnStrelciAsync() {
            return base.Channel.ReturnStrelciAsync();
        }
        
        public AIS_N3_WCF.User[] ReturnUseri() {
            return base.Channel.ReturnUseri();
        }
        
        public System.Threading.Tasks.Task<AIS_N3_WCF.User[]> ReturnUseriAsync() {
            return base.Channel.ReturnUseriAsync();
        }
        
        public AIS_N3_WCF.Strelec[] StrelciInKlub(string id) {
            return base.Channel.StrelciInKlub(id);
        }
        
        public System.Threading.Tasks.Task<AIS_N3_WCF.Strelec[]> StrelciInKlubAsync(string id) {
            return base.Channel.StrelciInKlubAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.StrelskaZveza.CheckUserResponse ConsoleApp1.StrelskaZveza.IStrelskaZveza.CheckUser(ConsoleApp1.StrelskaZveza.CheckUserRequest request) {
            return base.Channel.CheckUser(request);
        }
        
        public bool CheckUser(AIS_N3_WCF.User u, out bool admin) {
            ConsoleApp1.StrelskaZveza.CheckUserRequest inValue = new ConsoleApp1.StrelskaZveza.CheckUserRequest();
            inValue.u = u;
            ConsoleApp1.StrelskaZveza.CheckUserResponse retVal = ((ConsoleApp1.StrelskaZveza.IStrelskaZveza)(this)).CheckUser(inValue);
            admin = retVal.admin;
            return retVal.CheckUserResult;
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.StrelskaZveza.CheckUserResponse> CheckUserAsync(ConsoleApp1.StrelskaZveza.CheckUserRequest request) {
            return base.Channel.CheckUserAsync(request);
        }
    }
}
